### ISSUE TITLE
upload-charm fails if build-packages is defined in charmcraft.yaml

### ISSUE THREAD

**Issue by claudiubelu** [canonical/charming-actions#34]
If a charm has dependencies defined in its ``charmcraft.yaml`` file, it will try to ``apt-get install`` them. However, the ``upload-charm`` is hitting a Permission Denied error, which can be solved by just running ``sudo apt-get install`` instead.

sample build-packages in charmcraft.yaml:

```
parts:
  charm:
    build-packages:
      - git
      - python3-dev
      - libffi-dev
      - cargo
      - libssl-dev
```

Charm: https://github.com/claudiubelu/legend-juju-sdlc-server-operator
Job: https://github.com/claudiubelu/legend-juju-sdlc-server-operator/runs/5589471448?check_suite_focus=true
Logs: https://paste.ubuntu.com/p/pDgzgQMNm6/
