### ISSUE TITLE
Uploading charm fails when docker image is specified in metadata as upstream-resource

### ISSUE THREAD

**Issue by arturo-seijas** [canonical/charming-actions#60]
### Bug Description

When executing the the upload-action for a charm specifying an upstream-resource the exception attached occurs. This happens independently of the `upload`and `resource-overrides`options specified:

```
- name: Upload charm to charmhub
        uses: canonical/charming-actions/upload-charm@1.0.3
        with:
          credentials: ${{ secrets.CHARMHUB_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          channel: edge
          upload: false
```

The resources section of the charm metadata file is the following:
```
resources:
  indico-image:
    type: oci-image
    description: Docker image for Indico
    auto-fetch: true
  indico-nginx-image:
    type: oci-image
    description: Docker image for nginx Indico
    auto-fetch: true
  nginx-prometheus-exporter-image:
    type: oci-image
    description: Prometheus exporter for nginx
    auto-fetch: true
    upstream-source: nginx/nginx-prometheus-exporter:0.10.0
```

### To Reproduce

Run the following [workflow](https://github.com/canonical/indico-operator/blob/main/.github/workflows/on_push.yaml) of the [indico operator](https://github.com/canonical/indico-operator) changing the existing metadata contents for
```
resources:
  indico-image:
    type: oci-image
    description: Docker image for Indico
    auto-fetch: true
  indico-nginx-image:
    type: oci-image
    description: Docker image for nginx Indico
    auto-fetch: true
  nginx-prometheus-exporter-image:
    type: oci-image
    description: Prometheus exporter for nginx
    auto-fetch: true
    upstream-source: nginx/nginx-prometheus-exporter:0.10.0
```

### Environment

The issue popped-up while running a github workflow

### Relevant log output

```shell
/usr/bin/sudo snap install charmcraft --classic --channel latest/stable
charmcraft 2.0.0 from Canonical** installed
/usr/bin/sudo charmcraft pack --destructive-mode --quiet
/usr/bin/docker pull undefined
/usr/bin/docker pull nginx/nginx-prometheus-exporter:0.10.0
Using default tag: latest
***Error response from daemon: pull access denied for undefined, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Error: The process '/usr/bin/docker' failed with exit code 1
Error: Error: The process '/usr/bin/docker' failed with exit code 1
    at ExecState._setResult (/home/runner/work/_actions/canonical/charming-actions/1.0.3/dist/upload-charm/index.js:3276:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/canonical/charming-actions/1.0.3/dist/upload-charm/index.js:3259:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/canonical/charming-actions/1.0.3/dist/upload-charm/index.js:3153:27)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
No charmcraft logs generated, skipping artifact upload.***
0.10.0: Pulling from nginx/nginx-prometheus-exporter
6ca88092a[12](https://github.com/canonical/indico-operator/runs/7970721141?check_suite_focus=true#step:3:13)c: Pulling fs layer
aaea71c792be: Pulling fs layer
6ca88092a12c: Verifying Checksum
6ca88092a12c: Download complete
aaea71c792be: Verifying Checksum
aaea71c792be: Download complete
6ca88092a12c: Pull complete
aaea71c792be: Pull complete
Digest: sha256:1c6eba17d7768401ba1ed056101fc56ec3e3b5c82e508fdd8968fbcd96ec9574
Status: Downloaded newer image for nginx/nginx-prometheus-exporter:0.10.0
docker.io/nginx/nginx-prometheus-exporter:0.10.0
/snap/bin/charmcraft upload-resource --quiet indico nginx-prometheus-exporter-image --image nginx/nginx-prometheus-exporter:0.10.0
/snap/bin/charmcraft resource-revisions indico nginx-prometheus-exporter-image
Revision    Created at              Size
***5           2022-08-23T10:06:10Z    545B***
4           2022-08-22T09:51:04Z    545B
3           2022-08-19T15:10:27Z    545B
2           2022-08-19T[13](https://github.com/canonical/indico-operator/runs/7970721141?check_suite_focus=true#step:3:14):35:[32](https://github.com/canonical/indico-operator/runs/7970721141?check_suite_focus=true#step:3:33)Z    5[45](https://github.com/canonical/indico-operator/runs/7970721141?check_suite_focus=true#step:3:46)B
1           2022-08-19T13:32:26Z    5[45](https://github.com/canonical/indico-operator/runs/7970721141?check_suite_focus=true#step:3:46)B
```
