### ISSUE TITLE
canonical/charming-actions/check-libraries fails with exit code 1

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/charming-actions#62]
### Bug Description

get an issue in CI with unclear fail message:

> Also tested with 2.0.0 stable

```
Run canonical/charming-actions/check-libraries@2.0.0-rc2
/usr/bin/sudo snap install charmcraft --classic --channel latest/stable
charmcraft 2.0.0 from Canonical** installed
/snap/bin/charmcraft fetch-lib
No keyring found to store or retrieve credentials from.
Full execution log: '/home/runner/snap/charmcraft/common/cache/charmcraft/log/charmcraft-20220907-085012.313435.log'
Error: The process '/snap/bin/charmcraft' failed with exit code 1
Error: Error: The process '/snap/bin/charmcraft' failed with exit code 1
    at ExecState._setResult (/home/runner/work/_actions/canonical/charming-actions/2.0.0-rc2/dist/check-libraries/index.js:3276:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/canonical/charming-actions/2.0.0-rc2/dist/check-libraries/index.js:3259:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/canonical/charming-actions/2.0.0-rc2/dist/check-libraries/index.js:3153:27)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
```

### To Reproduce

we run following pipe on https://github.com/canonical/grafana-k8s-operator 
```yaml
  lib-check:
    name: Check libraries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check libs
        uses: canonical/charming-actions/check-libraries@2.0.0-rc2
        with:
          credentials: "${{ secrets.CHARMHUB_TOKEN }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
```

for example see checks in https://github.com/canonical/grafana-k8s-operator/pull/118

### Environment

-

### Relevant log output

```shell
see the bug description
```
