### ISSUE TITLE
[upload-charm] allow specifying Charmhub name

### ISSUE THREAD

**Issue by barrettj12** [canonical/charming-actions#77]
### Enhancement Proposal

The upload charm action doesn't have an input for setting the Charmhub upload name (analogous to `charmcraft upload --name`). We want to upload the charm under a different name for testing.

```
      - name: Upload charm to charmhub
        uses: canonical/charming-actions/upload-charm@1.0.0
        with:
          name: ....
```
