### ISSUE TITLE
New Action for uploading file resources

### ISSUE THREAD

**Issue by kian99** [canonical/charming-actions#99]
### Enhancement Proposal

This request is similar to #16, in the sense that it is looking to address a gap currently in the existing actions for charms with file resources.
The `upload-charm` readme contains the following,
>When uploading a charm with file resources, the most recent resource will be attached to the release. If you want to use a new resource, you'll have to cut a new resource revision prior to running the action.

If I'm not mistaken this would mean a workflow that wants to upload a resource + a charm in one go would need to look something like the below. This feels like extra boilerplate and a lack of consistency between the manual steps and the action. My suggestion would be a separate action dedicated to uploading file resources, that would prevent any breaking changes to the `upload-charm` action.
```
      - uses: actions/download-artifact@master
        with:
          name: <snap-name>
      - name: Install charmcraft
        run: sudo snap install charmcraft --channel=2.x/stable
      - name: Publish Charm Resource
        run: charmcraft upload-resource <charm-name> <resource-name> --filepath ./<file-name>
        env:
          CHARMCRAFT_AUTH: "${{ secrets.CHARMHUB_TOKEN }}"
      - name: Upload charm to charmhub
        uses: canonical/charming-actions/upload-charm@2.3.0
        with:
          credentials: "${{ secrets.CHARMHUB_TOKEN }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          channel: "${{ steps.channel.outputs.name }}"
```

Interested to hear alternate approaches to this issue.
